In [37]:
import pandas as pd
import numpy as np
import ast

# Load Data

In [38]:
with open(file='./data/frases.txt', mode='r', encoding='utf-8') as file:
    content = file.read()

- ast.parse(txt) analisa estrutura sintática.
- se o txt está em uma linguagem que o Python entende, ele lê como se fosse linguagem Python

In [39]:
tree = ast.parse(content)

* Objeto ast.Assign é um node
* Ele gerou um objeto Node para cada atribuição que encontrou no txt.
* São 3 atribuições, então são 3 objetos Assign.
* assignemnt → variável = alguma coisa

In [40]:
tree.body

[Assign(targets=[Name(id='textos_positivos', ctx=Store())], value=List(elts=[Constant(value='Bitcoin atinge novo recorde histórico! #Bitcoin #Cripto', kind=None), ..., Constant(value='Criptomoedas estão redefinindo o conceito de dinheiro.', kind=None)], ctx=Load()), type_comment=None),
 Assign(targets=[Name(id='textos_negativos', ctx=Store())], value=List(elts=[Constant(value='A volatilidade das criptomoedas está assustando os investidores.', kind=None), ..., Constant(value='As criptomoedas ainda são vistas com desconfiança por muitos.', kind=None)], ctx=Load()), type_comment=None),
 Assign(targets=[Name(id='textos_neutros', ctx=Store())], value=List(elts=[Constant(value='Regulamentações para criptomoedas estão sendo discutidas globalmente.', kind=None), ..., Constant(value='O desenvolvimento de criptomoedas está avançando rapidamente.', kind=None)], ctx=Load()), type_comment=None)]

In [41]:
tree.body[0]

Assign(targets=[Name(id='textos_positivos', ctx=Store())], value=List(elts=[Constant(value='Bitcoin atinge novo recorde histórico! #Bitcoin #Cripto', kind=None), ..., Constant(value='Criptomoedas estão redefinindo o conceito de dinheiro.', kind=None)], ctx=Load()), type_comment=None)

- Cada nó tem 2 atributos (targets e value)
- Target: nome da variável
- Value: lista

In [42]:
target_node_0 = tree.body[0].targets[0].id
target_node_0

'textos_positivos'

In [43]:
value_node_0 = ast.literal_eval(tree.body[0].value)
value_node_0

['Bitcoin atinge novo recorde histórico! #Bitcoin #Cripto',
 'Ethereum está revolucionando o mercado de contratos inteligentes.',
 'Cardano e Polkadot são as criptomoedas mais promissoras do ano.',
 'Investir em criptomoedas pode ser arriscado, mas também muito lucrativo.',
 'A adoção de Bitcoin como moeda legal em países emergentes está crescendo.',
 'Stablecoins oferecem uma alternativa menos volátil para investidores.',
 'O lançamento do Ethereum 2.0 promete melhorar a escalabilidade da rede.',
 'Grandes empresas começam a aceitar pagamentos em Bitcoin.',
 'Criptoativos são a nova fronteira da inovação financeira.',
 'Investidores institucionais estão começando a entrar no mercado de criptos.',
 'Bitcoin pode chegar a valer mais de 100 mil dólares nos próximos anos.',
 'Criptomoedas estão mudando a forma como vemos o dinheiro.',
 'É possível ganhar dinheiro com criptomoedas?',
 'Blockchain pode revolucionar diversos setores além das criptomoedas.',
 'O interesse em criptomoedas está crescendo entre jovens investidores.',
 'Muitos acreditam que o Bitcoin é o ouro digital.',
 'A aceitação de Bitcoin por empresas está se tornando mais comum.',
 'Novas tecnologias blockchain estão sendo desenvolvidas para melhorar a eficiência.',
 'O mercado de criptomoedas está amadurecendo rapidamente.',
 'Mais países estão considerando legalizar o uso de criptomoedas.',
 'Investidores que acreditam em Bitcoin estão vendo retornos significativos.',
 'Criptomoedas oferecem uma nova forma de liberdade financeira.',
 'A blockchain está trazendo transparência para vários setores.',
 'Investir em criptoativos pode ser uma excelente estratégia de longo prazo.',
 'O aumento da adoção de criptomoedas está impulsionando o mercado.',
 'Criptoativos estão sendo vistos como uma nova classe de ativos.',
 'O Bitcoin é considerado uma proteção contra a inflação.',
 'Empresas de tecnologia estão investindo pesado em blockchain.',
 'O futuro das finanças pode estar na descentralização das criptomoedas.',
 'O mercado cripto está cada vez mais regulamentado, o que traz segurança.',
 'Bitcoin está sendo utilizado como reserva de valor em muitos países.',
 'A infraestrutura de criptomoedas está se expandindo globalmente.',
 'O desenvolvimento de novas criptomoedas está impulsionando a inovação.',
 'Muitas pessoas estão mudando suas vidas com investimentos em cripto.',
 'A adoção institucional de criptomoedas está acelerando.',
 'A volatilidade do mercado cripto cria oportunidades lucrativas.',
 'O mercado de NFTs está criando novas oportunidades para artistas.',
 'Os contratos inteligentes do Ethereum estão mudando a forma de fazer negócios.',
 'As criptomoedas podem democratizar o acesso ao sistema financeiro.',
 'Criptoativos são a próxima grande inovação no mercado financeiro.',
 'Investidores de longo prazo estão otimistas com o futuro do Bitcoin.',
 'A blockchain pode resolver muitos problemas de confiança no mercado.',
 'A escalabilidade das criptomoedas está melhorando com novas soluções.',
 'Criptoativos oferecem diversificação em portfólios de investimento.',
 'Muitos especialistas acreditam no potencial de valorização do Bitcoin.',
 'As criptomoedas oferecem alternativas ao sistema bancário tradicional.',
 'Os avanços na tecnologia blockchain estão criando novos mercados.',
 'O uso de criptomoedas está crescendo exponencialmente.',
 'A inovação no mercado cripto está apenas começando.',
 'Criptomoedas estão redefinindo o conceito de dinheiro.']

- O atributo value possui o atributo ELTS que é uma lista de elementos (constantes).
- Cada constante é uma linha de uma Lista

In [44]:
tree.body[0].value.elts

[Constant(value='Bitcoin atinge novo recorde histórico! #Bitcoin #Cripto', kind=None),
 Constant(value='Ethereum está revolucionando o mercado de contratos inteligentes.', kind=None),
 Constant(value='Cardano e Polkadot são as criptomoedas mais promissoras do ano.', kind=None),
 Constant(value='Investir em criptomoedas pode ser arriscado, mas também muito lucrativo.', kind=None),
 Constant(value='A adoção de Bitcoin como moeda legal em países emergentes está crescendo.', kind=None),
 Constant(value='Stablecoins oferecem uma alternativa menos volátil para investidores.', kind=None),
 Constant(value='O lançamento do Ethereum 2.0 promete melhorar a escalabilidade da rede.', kind=None),
 Constant(value='Grandes empresas começam a aceitar pagamentos em Bitcoin.', kind=None),
 Constant(value='Criptoativos são a nova fronteira da inovação financeira.', kind=None),
 Constant(value='Investidores institucionais estão começando a entrar no mercado de criptos.', kind=None),
 Constant(value='Bitcoin pode chegar a valer mais de 100 mil dólares nos próximos anos.', kind=None),
 Constant(value='Criptomoedas estão mudando a forma como vemos o dinheiro.', kind=None),
 Constant(value='É possível ganhar dinheiro com criptomoedas?', kind=None),
 Constant(value='Blockchain pode revolucionar diversos setores além das criptomoedas.', kind=None),
 Constant(value='O interesse em criptomoedas está crescendo entre jovens investidores.', kind=None),
 Constant(value='Muitos acreditam que o Bitcoin é o ouro digital.', kind=None),
 Constant(value='A aceitação de Bitcoin por empresas está se tornando mais comum.', kind=None),
 Constant(value='Novas tecnologias blockchain estão sendo desenvolvidas para melhorar a eficiência.', kind=None),
 Constant(value='O mercado de criptomoedas está amadurecendo rapidamente.', kind=None),
 Constant(value='Mais países estão considerando legalizar o uso de criptomoedas.', kind=None),
 Constant(value='Investidores que acreditam em Bitcoin estão vendo retornos significativos.', kind=None),
 Constant(value='Criptomoedas oferecem uma nova forma de liberdade financeira.', kind=None),
 Constant(value='A blockchain está trazendo transparência para vários setores.', kind=None),
 Constant(value='Investir em criptoativos pode ser uma excelente estratégia de longo prazo.', kind=None),
 Constant(value='O aumento da adoção de criptomoedas está impulsionando o mercado.', kind=None),
 Constant(value='Criptoativos estão sendo vistos como uma nova classe de ativos.', kind=None),
 Constant(value='O Bitcoin é considerado uma proteção contra a inflação.', kind=None),
 Constant(value='Empresas de tecnologia estão investindo pesado em blockchain.', kind=None),
 Constant(value='O futuro das finanças pode estar na descentralização das criptomoedas.', kind=None),
 Constant(value='O mercado cripto está cada vez mais regulamentado, o que traz segurança.', kind=None),
 Constant(value='Bitcoin está sendo utilizado como reserva de valor em muitos países.', kind=None),
 Constant(value='A infraestrutura de criptomoedas está se expandindo globalmente.', kind=None),
 Constant(value='O desenvolvimento de novas criptomoedas está impulsionando a inovação.', kind=None),
 Constant(value='Muitas pessoas estão mudando suas vidas com investimentos em cripto.', kind=None),
 Constant(value='A adoção institucional de criptomoedas está acelerando.', kind=None),
 Constant(value='A volatilidade do mercado cripto cria oportunidades lucrativas.', kind=None),
 Constant(value='O mercado de NFTs está criando novas oportunidades para artistas.', kind=None),
 Constant(value='Os contratos inteligentes do Ethereum estão mudando a forma de fazer negócios.', kind=None),
 Constant(value='As criptomoedas podem democratizar o acesso ao sistema financeiro.', kind=None),
 Constant(value='Criptoativos são a próxima grande inovação no mercado financeiro.', kind=None),
 Constant(value='Investidores de longo prazo estão otimistas com o futuro do Bitcoin.', kind=None),
 Constant(value='A blockchain pode resolver muitos problemas de confiança no mercado.', kind=None),
 Constant(value='A escalabilidade das criptomoedas está melhorando com novas soluções.', kind=None),
 Constant(value='Criptoativos oferecem diversificação em portfólios de investimento.', kind=None),
 Constant(value='Muitos especialistas acreditam no potencial de valorização do Bitcoin.', kind=None),
 Constant(value='As criptomoedas oferecem alternativas ao sistema bancário tradicional.', kind=None),
 Constant(value='Os avanços na tecnologia blockchain estão criando novos mercados.', kind=None),
 Constant(value='O uso de criptomoedas está crescendo exponencialmente.', kind=None),
 Constant(value='A inovação no mercado cripto está apenas começando.', kind=None),
 Constant(value='Criptomoedas estão redefinindo o conceito de dinheiro.', kind=None)]

In [45]:
def gera_dados(arvore):
    '''Extrai nome da lista e valores da lista
    de um arquivo txt'''
    dados = []

    for node in arvore.body:
        nome = node.targets[0].id
        
        for row in node.value.elts:
            dados.append({'label': nome,
                          'value': row.value})
    return dados

In [46]:
data = gera_dados(tree)

In [47]:
type(data)

list

In [48]:
data

[{'label': 'textos_positivos',
  'value': 'Bitcoin atinge novo recorde histórico! #Bitcoin #Cripto'},
 {'label': 'textos_positivos',
  'value': 'Ethereum está revolucionando o mercado de contratos inteligentes.'},
 {'label': 'textos_positivos',
  'value': 'Cardano e Polkadot são as criptomoedas mais promissoras do ano.'},
 {'label': 'textos_positivos',
  'value': 'Investir em criptomoedas pode ser arriscado, mas também muito lucrativo.'},
 {'label': 'textos_positivos',
  'value': 'A adoção de Bitcoin como moeda legal em países emergentes está crescendo.'},
 {'label': 'textos_positivos',
  'value': 'Stablecoins oferecem uma alternativa menos volátil para investidores.'},
 {'label': 'textos_positivos',
  'value': 'O lançamento do Ethereum 2.0 promete melhorar a escalabilidade da rede.'},
 {'label': 'textos_positivos',
  'value': 'Grandes empresas começam a aceitar pagamentos em Bitcoin.'},
 {'label': 'textos_positivos',
  'value': 'Criptoativos são a nova fronteira da inovação financeira.'},
 {'label': 'textos_positivos',
  'value': 'Investidores institucionais estão começando a entrar no mercado de criptos.'},
 {'label': 'textos_positivos',
  'value': 'Bitcoin pode chegar a valer mais de 100 mil dólares nos próximos anos.'},
 {'label': 'textos_positivos',
  'value': 'Criptomoedas estão mudando a forma como vemos o dinheiro.'},
 {'label': 'textos_positivos',
  'value': 'É possível ganhar dinheiro com criptomoedas?'},
 {'label': 'textos_positivos',
  'value': 'Blockchain pode revolucionar diversos setores além das criptomoedas.'},
 {'label': 'textos_positivos',
  'value': 'O interesse em criptomoedas está crescendo entre jovens investidores.'},
 {'label': 'textos_positivos',
  'value': 'Muitos acreditam que o Bitcoin é o ouro digital.'},
 {'label': 'textos_positivos',
  'value': 'A aceitação de Bitcoin por empresas está se tornando mais comum.'},
 {'label': 'textos_positivos',
  'value': 'Novas tecnologias blockchain estão sendo desenvolvidas para melhorar a eficiência.'},
 {'label': 'textos_positivos',
  'value': 'O mercado de criptomoedas está amadurecendo rapidamente.'},
 {'label': 'textos_positivos',
  'value': 'Mais países estão considerando legalizar o uso de criptomoedas.'},
 {'label': 'textos_positivos',
  'value': 'Investidores que acreditam em Bitcoin estão vendo retornos significativos.'},
 {'label': 'textos_positivos',
  'value': 'Criptomoedas oferecem uma nova forma de liberdade financeira.'},
 {'label': 'textos_positivos',
  'value': 'A blockchain está trazendo transparência para vários setores.'},
 {'label': 'textos_positivos',
  'value': 'Investir em criptoativos pode ser uma excelente estratégia de longo prazo.'},
 {'label': 'textos_positivos',
  'value': 'O aumento da adoção de criptomoedas está impulsionando o mercado.'},
 {'label': 'textos_positivos',
  'value': 'Criptoativos estão sendo vistos como uma nova classe de ativos.'},
 {'label': 'textos_positivos',
  'value': 'O Bitcoin é considerado uma proteção contra a inflação.'},
 {'label': 'textos_positivos',
  'value': 'Empresas de tecnologia estão investindo pesado em blockchain.'},
 {'label': 'textos_positivos',
  'value': 'O futuro das finanças pode estar na descentralização das criptomoedas.'},
 {'label': 'textos_positivos',
  'value': 'O mercado cripto está cada vez mais regulamentado, o que traz segurança.'},
 {'label': 'textos_positivos',
  'value': 'Bitcoin está sendo utilizado como reserva de valor em muitos países.'},
 {'label': 'textos_positivos',
  'value': 'A infraestrutura de criptomoedas está se expandindo globalmente.'},
 {'label': 'textos_positivos',
  'value': 'O desenvolvimento de novas criptomoedas está impulsionando a inovação.'},
 {'label': 'textos_positivos',
  'value': 'Muitas pessoas estão mudando suas vidas com investimentos em cripto.'},
 {'label': 'textos_positivos',
  'value': 'A adoção institucional de criptomoedas está acelerando.'},
 {'label': 'textos_positivos',
  'value': 'A volatilidade do mercado cripto cria oportunidades lucrativas.'},
 {'label': 'textos_positivos',
  'value': 'O mercado de NFTs está criando novas oportunidades para artistas.'},
 {'label': 'textos_positivos',
  'value': 'Os contratos inteligentes do Ethereum estão mudando a forma de fazer negócios.'},
 {'label': 'textos_positivos',
  'value': 'As criptomoedas podem democratizar o acesso ao sistema financeiro.'},
 {'label': 'textos_positivos',
  'value': 'Criptoativos são a próxima grande inovação no mercado financeiro.'},
 {'label': 'textos_positivos',
  'value': 'Investidores de longo prazo estão otimistas com o futuro do Bitcoin.'},
 {'label': 'textos_positivos',
  'value': 'A blockchain pode resolver muitos problemas de confiança no mercado.'},
 {'label': 'textos_positivos',
  'value': 'A escalabilidade das criptomoedas está melhorando com novas soluções.'},
 {'label': 'textos_positivos',
  'value': 'Criptoativos oferecem diversificação em portfólios de investimento.'},
 {'label': 'textos_positivos',
  'value': 'Muitos especialistas acreditam no potencial de valorização do Bitcoin.'},
 {'label': 'textos_positivos',
  'value': 'As criptomoedas oferecem alternativas ao sistema bancário tradicional.'},
 {'label': 'textos_positivos',
  'value': 'Os avanços na tecnologia blockchain estão criando novos mercados.'},
 {'label': 'textos_positivos',
  'value': 'O uso de criptomoedas está crescendo exponencialmente.'},
 {'label': 'textos_positivos',
  'value': 'A inovação no mercado cripto está apenas começando.'},
 {'label': 'textos_positivos',
  'value': 'Criptomoedas estão redefinindo o conceito de dinheiro.'},
 {'label': 'textos_negativos',
  'value': 'A volatilidade das criptomoedas está assustando os investidores.'},
 {'label': 'textos_negativos',
  'value': 'Hackers roubam milhões em criptoativos de exchange descentralizada.'},
 {'label': 'textos_negativos',
  'value': 'Muitos ainda desconfiam da segurança das criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'A mineração de criptomoedas consome muita energia elétrica.'},
 {'label': 'textos_negativos',
  'value': 'Reguladores estão de olho nas exchanges de criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'O mercado de criptomoedas é extremamente volátil.'},
 {'label': 'textos_negativos',
  'value': 'Muitos especialistas acreditam que o Bitcoin é uma bolha.'},
 {'label': 'textos_negativos',
  'value': 'O futuro das criptomoedas depende de regulamentações claras.'},
 {'label': 'textos_negativos',
  'value': 'Criptomoedas são usadas para lavagem de dinheiro?'},
 {'label': 'textos_negativos',
  'value': 'A volatilidade do Bitcoin é uma faca de dois gumes.'},
 {'label': 'textos_negativos',
  'value': 'A regulamentação pode sufocar o crescimento das criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'Alguns países estão banindo o uso de criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'Os investidores estão preocupados com as quedas recentes das criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'O uso ilícito de criptomoedas está aumentando.'},
 {'label': 'textos_negativos',
  'value': 'A adoção de criptomoedas está enfrentando resistência em muitos setores.'},
 {'label': 'textos_negativos',
  'value': 'Hackers continuam a explorar vulnerabilidades em exchanges de cripto.'},
 {'label': 'textos_negativos',
  'value': 'A segurança das criptomoedas continua a ser uma preocupação.'},
 {'label': 'textos_negativos',
  'value': 'A falta de regulamentação clara está afastando investidores tradicionais.'},
 {'label': 'textos_negativos',
  'value': 'As quedas acentuadas do Bitcoin estão causando pânico no mercado.'},
 {'label': 'textos_negativos',
  'value': 'Muitos investidores perderam dinheiro com a queda das criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'A mineração de criptomoedas está enfrentando críticas ambientais.'},
 {'label': 'textos_negativos',
  'value': 'O mercado cripto é alvo constante de ataques cibernéticos.'},
 {'label': 'textos_negativos',
  'value': 'A volatilidade das criptomoedas pode causar grandes perdas.'},
 {'label': 'textos_negativos',
  'value': 'Os críticos dizem que as criptomoedas são uma moda passageira.'},
 {'label': 'textos_negativos',
  'value': 'O risco de fraude em transações cripto é alto.'},
 {'label': 'textos_negativos',
  'value': 'Criptomoedas podem ser usadas para atividades ilícitas.'},
 {'label': 'textos_negativos',
  'value': 'A regulação estrita pode dificultar a inovação no setor cripto.'},
 {'label': 'textos_negativos',
  'value': 'Alguns bancos estão se recusando a aceitar criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'A instabilidade do mercado cripto é um grande desafio.'},
 {'label': 'textos_negativos',
  'value': 'A adoção em massa de criptomoedas pode ser lenta e difícil.'},
 {'label': 'textos_negativos',
  'value': 'Muitos acreditam que o mercado cripto é uma bolha prestes a estourar.'},
 {'label': 'textos_negativos',
  'value': 'A falta de proteção ao consumidor no mercado cripto é preocupante.'},
 {'label': 'textos_negativos',
  'value': 'Os escândalos em exchanges cripto estão afetando a confiança dos investidores.'},
 {'label': 'textos_negativos',
  'value': 'A resistência dos governos às criptomoedas pode ser um obstáculo.'},
 {'label': 'textos_negativos',
  'value': 'A adoção de criptomoedas está sendo barrada por problemas regulatórios.'},
 {'label': 'textos_negativos',
  'value': 'O mercado cripto é conhecido por suas grandes oscilações de preço.'},
 {'label': 'textos_negativos',
  'value': 'Hackers estão roubando bilhões em criptoativos.'},
 {'label': 'textos_negativos',
  'value': 'O uso de criptomoedas em atividades criminosas está aumentando.'},
 {'label': 'textos_negativos',
  'value': 'A instabilidade das criptomoedas é um problema constante.'},
 {'label': 'textos_negativos',
  'value': 'Os reguladores estão pressionando por maior controle sobre o mercado cripto.'},
 {'label': 'textos_negativos',
  'value': 'A mineração de Bitcoin está enfrentando dificuldades devido ao alto consumo de energia.'},
 {'label': 'textos_negativos',
  'value': 'A incerteza regulatória está afastando grandes investidores das criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'O uso de criptomoedas em esquemas fraudulentos está em alta.'},
 {'label': 'textos_negativos',
  'value': 'As perdas no mercado cripto estão causando preocupações entre investidores.'},
 {'label': 'textos_negativos',
  'value': 'Muitos veem as criptomoedas como uma aposta arriscada.'},
 {'label': 'textos_negativos',
  'value': 'O medo de perder dinheiro está impedindo a adoção de criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'A falta de infraestrutura adequada está dificultando o crescimento das criptomoedas.'},
 {'label': 'textos_negativos',
  'value': 'As criptomoedas ainda são vistas com desconfiança por muitos.'},
 {'label': 'textos_neutros',
  'value': 'Regulamentações para criptomoedas estão sendo discutidas globalmente.'},
 {'label': 'textos_neutros',
  'value': 'Governos consideram a criação de suas próprias moedas digitais.'},
 {'label': 'textos_neutros',
  'value': 'A blockchain pode ser usada para mais do que apenas criptomoedas.'},
 {'label': 'textos_neutros',
  'value': 'Como proteger suas criptomoedas de hackers e fraudes?'},
 {'label': 'textos_neutros',
  'value': 'A mineração de criptomoedas é um tópico em debate.'},
 {'label': 'textos_neutros',
  'value': 'A tecnologia blockchain está sendo explorada em vários setores.'},
 {'label': 'textos_neutros',
  'value': 'Os investidores estão atentos às mudanças no mercado de criptomoedas.'},
 {'label': 'textos_neutros',
  'value': 'O futuro das criptomoedas é incerto, mas promissor.'},
 {'label': 'textos_neutros',
  'value': 'As criptomoedas estão ganhando espaço, mas ainda enfrentam desafios.'},
 {'label': 'textos_neutros',
  'value': 'A regulamentação do mercado cripto é inevitável.'},
 {'label': 'textos_neutros',
  'value': 'O interesse por NFTs está crescendo, mas com cautela.'},
 {'label': 'textos_neutros',
  'value': 'A volatilidade das criptomoedas é um fato conhecido.'},
 {'label': 'textos_neutros',
  'value': 'A adoção de criptomoedas está em ascensão, apesar dos desafios.'},
 {'label': 'textos_neutros',
  'value': 'As stablecoins estão ganhando popularidade como alternativa às criptomoedas voláteis.'},
 {'label': 'textos_neutros',
  'value': 'O mercado cripto é dinâmico e está em constante evolução.'},
 {'label': 'textos_neutros',
  'value': 'A blockchain é a tecnologia subjacente às criptomoedas.'},
 {'label': 'textos_neutros',
  'value': 'A regulação do mercado cripto ainda está em fase inicial.'},
 {'label': 'textos_neutros',
  'value': 'A adoção de criptomoedas varia amplamente entre os países.'},
 {'label': 'textos_neutros',
  'value': 'O uso de criptomoedas está se expandindo para além do investimento.'},
 {'label': 'textos_neutros',
  'value': 'A mineração de criptomoedas é uma atividade global.'},
 {'label': 'textos_neutros',
  'value': 'As criptomoedas estão criando novas oportunidades, mas também riscos.'},
 {'label': 'textos_neutros',
  'value': 'A tecnologia blockchain está sendo adotada em diferentes indústrias.'},
 {'label': 'textos_neutros',
  'value': 'As exchanges de criptomoedas estão evoluindo para se adequar às regulamentações.'},
 {'label': 'textos_neutros',
  'value': 'O uso de criptomoedas está crescendo, mas ainda é limitado.'},
 {'label': 'textos_neutros',
  'value': 'A educação financeira sobre criptomoedas é fundamental para a adoção.'},
 {'label': 'textos_neutros',
  'value': 'A aceitação de criptomoedas como pagamento está aumentando lentamente.'},
 {'label': 'textos_neutros',
  'value': 'A volatilidade é uma característica intrínseca das criptomoedas.'},
 {'label': 'textos_neutros',
  'value': 'O impacto ambiental da mineração de criptomoedas é uma preocupação crescente.'},
 {'label': 'textos_neutros',
  'value': 'A infraestrutura de suporte a criptomoedas está se desenvolvendo.'},
 {'label': 'textos_neutros',
  'value': 'As criptomoedas estão se tornando parte do mercado financeiro tradicional.'},
 {'label': 'textos_neutros',
  'value': 'A adoção de criptomoedas está impulsionando o desenvolvimento de novas tecnologias.'},
 {'label': 'textos_neutros',
  'value': 'O mercado cripto está em transformação constante.'},
 {'label': 'textos_neutros',
  'value': 'A blockchain oferece uma forma segura de registrar transações.'},
 {'label': 'textos_neutros',
  'value': 'O mercado de NFTs é uma nova fronteira para colecionadores e criadores.'},
 {'label': 'textos_neutros',
  'value': 'A evolução das criptomoedas depende de inovações tecnológicas contínuas.'},
 {'label': 'textos_neutros',
  'value': 'A popularidade das criptomoedas está aumentando, mas com desafios.'},
 {'label': 'textos_neutros',
  'value': 'A tecnologia por trás das criptomoedas está sendo aprimorada.'},
 {'label': 'textos_neutros',
  'value': 'O mercado cripto é relativamente jovem, mas está crescendo.'},
 {'label': 'textos_neutros',
  'value': 'A aceitação global das criptomoedas ainda enfrenta obstáculos.'},
 {'label': 'textos_neutros',
  'value': 'O desenvolvimento de criptomoedas está avançando rapidamente.'}]

In [49]:
n = len(data)
n

138

In [50]:
# Cria uma coluna com datas aleatórias
dates = pd.date_range(start='2020-01-01', periods = n)

# Cria o Dataframe

In [51]:
df = pd.DataFrame(data = {'id': range(n),
                          'data': dates,
                          'texto': [d['value'] for d in data],
                          'sentimento': [d['label'] for d in data]}
)

In [52]:
df

,id,data,texto,sentimento
0,0,2020-01-01,Bitcoin atinge novo recorde histórico! #Bitcoi...,textos_positivos
1,1,2020-01-02,Ethereum está revolucionando o mercado de cont...,textos_positivos
2,2,2020-01-03,Cardano e Polkadot são as criptomoedas mais pr...,textos_positivos
3,3,2020-01-04,"Investir em criptomoedas pode ser arriscado, m...",textos_positivos
4,4,2020-01-05,A adoção de Bitcoin como moeda legal em países...,textos_positivos
...,...,...,...,...
133,133,2020-05-13,A popularidade das criptomoedas está aumentand...,textos_neutros
134,134,2020-05-14,A tecnologia por trás das criptomoedas está se...,textos_neutros
135,135,2020-05-15,"O mercado cripto é relativamente jovem, mas es...",textos_neutros
136,136,2020-05-16,A aceitação global das criptomoedas ainda enfr...,textos_neutros
137,137,2020-05-17,O desenvolvimento de criptomoedas está avançan...,textos_neutros

In [53]:
df['sentimento'] = df['sentimento'].map({'textos_positivos': 'positivo',
                                        'textos_negativos': 'negativo',
                                        'textos_neutros': 'neutro'}
)

In [54]:
df

,id,data,texto,sentimento
0,0,2020-01-01,Bitcoin atinge novo recorde histórico! #Bitcoi...,positivo
1,1,2020-01-02,Ethereum está revolucionando o mercado de cont...,positivo
2,2,2020-01-03,Cardano e Polkadot são as criptomoedas mais pr...,positivo
3,3,2020-01-04,"Investir em criptomoedas pode ser arriscado, m...",positivo
4,4,2020-01-05,A adoção de Bitcoin como moeda legal em países...,positivo
...,...,...,...,...
133,133,2020-05-13,A popularidade das criptomoedas está aumentand...,neutro
134,134,2020-05-14,A tecnologia por trás das criptomoedas está se...,neutro
135,135,2020-05-15,"O mercado cripto é relativamente jovem, mas es...",neutro
136,136,2020-05-16,A aceitação global das criptomoedas ainda enfr...,neutro
137,137,2020-05-17,O desenvolvimento de criptomoedas está avançan...,neutro

# Salva o df em um arquivo csv

In [55]:
type(df)

pandas.DataFrame

In [56]:
df.to_csv(
    path_or_buf='./data/dataset.csv',
    index = False,
    header=df.columns,
    encoding='utf-8')